### ISSUE TITLE
'charmap' codec can't decode byte 0x98 in position 31319

### ISSUE THREAD

**Issue by MGKovalev** [kirillignatyev/wildberries-parser-in-python#1]
Hellow 
parse catalog function return error 

Traceback (most recent call last):
  File "C:\PyProject\wbparser\wildberries-parser-in-python-main\wbparser.py", line 416, in <module>
    app.run_parser()
  File "C:\PyProject\wbparser\wildberries-parser-in-python-main\wbparser.py", line 396, in run_parser
    processed_catalogue = self.process_catalogue(local_catalogue_path)
  File "C:\PyProject\wbparser\wildberries-parser-in-python-main\wbparser.py", line 173, in process_catalogue
    self.traverse_json(json.load(my_file), catalogue)
  File "C:\Python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 31319: character maps to <undefined>

Process finished with exit code 1

**Comment by kirillignatyev** [comment]
Hi there!
Check the recent fix ([d0bb75b](https://github.com/kirillignatyev/wildberries-parser-in-python/commit/d0bb75b6b3e97b67fb9c8d9706364b039e140366)), please.
