### ISSUE TITLE
Error: json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by sergebsn** [kirillignatyev/wildberries-parser-in-python#2]
Вылетает ошибка, как бы не вводил группу , все время ошибка:

Введите 1 для парсинга категории целиком,
        2 — по ключевым словам: 1
Каталог сохранен: wb_catalogue.json
Введите название категории или ссылку: Верхняя одежда
Найдена категория: Верхняя одежда
Загружаю товары со страницы 1
Traceback (most recent call last):
  File "wbparser.py", line 416, in <module>
    app.run_parser()
  File "wbparser.py", line 404, in run_parser
    self.get_all_products_in_category(category_data)
  File "wbparser.py", line 293, in get_all_products_in_category
    if self.add_data_from_page(url):
  File "wbparser.py", line 256, in add_data_from_page
    response = requests.get(url, headers=self.headers).json()
  File "/home/serge/anaconda3/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/serge/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/serge/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/serge/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kirillignatyev** [comment]
Постарался исправить в последнем фиксе ([d0bb75b](https://github.com/kirillignatyev/wildberries-parser-in-python/commit/d0bb75b6b3e97b67fb9c8d9706364b039e140366)).
